jupyter:
    build: .
    command: /usr/share/datahub/tests/datahub-base-notebook/test.sh
    ports:
    - "8889:8888"
sut:
    image: elgalu/selenium:3.141
    volumes:
    - ./tests:/opt/datahub-base-notebook
    user: root
    links:
    - jupyter
    command:
    - python
    - /opt/datahub-base-notebook/test-ui.py
