# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Set Image Name
        run: |
          IMAGE_NAME="'${{secrets.DOCKERHUB_USERNAME}}'/${GITHUB_REPOSITORY##*/}"
          IMAGE_NAME="${IMAGE_NAME}:${GITHUB_SHA:0:7}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          GHCR_IMAGE_NAME="'${{secrets.GHCR_USERNAME}}'/${GITHUB_REPOSITORY##*/}"
          GHCR_IMAGE_NAME="${GHCR_IMAGE_NAME}:${GITHUB_SHA:0:7}"
          echo "GHCR_IMAGE_NAME=${GHCR_IMAGE_NAME}" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build --rm --force-rm -t "${IMAGE_NAME}" .
          echo -n "Built image size: "
          docker images "${IMAGE_NAME}" --format "{{.Size}}"
      - name: Login to Dockerhub
        run: >
          echo '${{secrets.DOCKERHUB_PASSWORD}}' | docker login --username
          '${{secrets.DOCKERHUB_USERNAME}}' --password-stdin
      - name: Push to Dockerhub
        run: docker push "${IMAGE_NAME}"
      - name: Login to Github Container Registry
        run: >
          echo '${{secrets.GHCR_PAT}}' | docker login --username
          '${{secrets.GHCR_USERNAME}}' --password-stdin
      - name: Push to Github Container Registry
        run: |
          docker tag "${IMAGE_NAME}" "ghcr.io/${GHCR_IMAGE_NAME}"
          docker push "ghcr.io/${GHCR_IMAGE_NAME}"
